name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ develop, main ]

env:
  REGISTRY_NAMESPACE: alihk
  ACR_REGISTRY: registry.cn-hongkong.aliyuncs.com
  APP_NAME: gada
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Aliyun registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker build image
        run: |
          docker build --file Dockerfile -t $ACR_REGISTRY/$REGISTRY_NAMESPACE/$APP_NAME:$IMAGE_TAG .

      - name: Docker push for ACR
        run: |
          docker push $ACR_REGISTRY/$REGISTRY_NAMESPACE/$APP_NAME:$IMAGE_TAG

      - name: Deploy to Ubuntu server via SSH
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_NAME: ${{ env.ACR_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.APP_NAME }}
          DEPLOY_TAG: ${{ env.IMAGE_TAG }}
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEPLOY_NAME,DEPLOY_TAG
          script: |
            cd /data/gada  || true
            echo "$IMAGE_TAG"
            bash update.sh $DEPLOY_NAME $DEPLOY_TAG
            echo "script complete"
